### PR TITLE
🪥 some cleanup of repo defaults

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <christoph@goern.name>

### CODE REVIEW

**Comment by goern** [comment]
All, please have a look by this Wed and let me know if you want to be involved any further

/assign codificat
/assign cooktheryan
/assign durandom
/assign goern
/assign gregory-pereira
/assign harshad16
/assign hpdempsey
/assign quaid
/assign rbo
/assign schwesig
/assign tumido

**Comment by durandom** [comment]
👍  
do we want to manage involvement by managing GH groups?

**Comment by rbo** [comment]
Count me in

**Comment by tumido** [comment]
Count me in as well! I won't be involved as much as I used to, but I can review PRs and stuff...

**Comment by harshad16** [comment]
I m unsure, what involvement is being asked for @goern 
can you please provide some information?

**Comment by goern** [comment]
It's no commitments or strings attached. Go for fun, knowledge and experience...

**Comment by harshad16** [comment]
i m happy to provide my knowledge and past experience, however, I won't be able to spend any time on implementation.

**Comment by codificat** [comment]
Late replying here, but I'm always in for fun, knowledge and experience :smiley:

**Pull request merged**
